version: "3.7"
services:
  postgres:
    build:
      context: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 3002:3002
    depends_on:
      - postgres
  redis:
    image: redis:3.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  pgdata:
  redis:
